-- Total customers by countries in descending order

SELECT
	country,
	COUNT(customer_id) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Total customers by gender in descending order

SELECT
	gender,
	COUNT(customer_id) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Total products by category ordered in descending order

SELECT
	category,
	COUNT(product_id) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- The average costs in each category in descending order, rounded to 2 dicimal points 

SELECT
	category,
	ROUND(AVG(cost)) as avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;

-- Total revenue generated for each category in descending order

SELECT
	p.category,
	SUM(s.sales_amount) AS revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON s.product_key = p.product_key
GROUP BY category
ORDER BY revenue DESC;

-- Total revenue generated by each customer in descending order  

SELECT
	c.customer_id,
	c.first_name,
	c.last_name,
	SUM(s.sales_amount) AS revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP BY c.customer_id,
         c.first_name,
		 c.last_name
ORDER BY revenue DESC;

-- Distribution of sold products' quantity across countries in descending order

SELECT
	c.country,
	SUM(s.quantity) AS total_quantity
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP BY country
ORDER BY total_quantity DESC;
